### PR TITLE
Add support for reading Tags from Gherkin feature files

### LINKED ISSUE #425: Support for reading Tags from Gherkin feature files
The standard Tag importer supports reading tags from comments in a wide array of source code files.
Sadly, it is currently not possible to read Tags from `.feature` files as used with the [Gherkin language](https://cucumber.io/docs/gherkin/).

Gherkin also uses the `#` character to mark a line as a comment line. It should therefore be very easy to add support for _feature_ files because all that would need to be done is add `feature` to the standard Tag importer's list of supported file extensions.

### PR DESCRIPTION
**Pull request by sophokles73**
Added "feature" to the list of supported file extensions so that
the standard Tag importer can now extract Tags from comments in
"feature" files as used by Gherkin.

This addresses #425

Closes #425

### CODE REVIEW

**Review by kaklakariada — CHANGES_REQUESTED** [review]
Looks good.
Please create an entry in the latest changelog file. Maybe you need to create a new one for the upcoming version.

**Comment by sophokles73** [comment]
> Looks good. Please create an entry in the latest changelog file. Maybe you need to create a new one for the upcoming version.

Are you referring to [this file](https://github.com/itsallcode/openfasttrace/blob/main/doc/CHANGELOG.md)? If so, then IMHO you will need to fill in the gaps first for versions (3.6.0,4.0.2]. Or do you want to me to simply add the change to the _Unreleased_ section?

**Comment by sophokles73** [comment]
Or do you mean creating a new file for version 4.1.0 [in this folder](https://github.com/itsallcode/openfasttrace/tree/main/doc/changes)?

**Comment by kaklakariada** [comment]
Good point! CHANGELOG.md is deprecated. I created https://github.com/itsallcode/openfasttrace/issues/427 to migrate its content and remove it.

Please increment the version and add the changelog as described in the [developer guide](https://github.com/itsallcode/openfasttrace/blob/main/doc/developer_guide.md#prepare-the-release) (no need to create a new PR).

Once the PR is merged to `main`, the build should automatically create a release.

**Review by kaklakariada — APPROVED** [review]

**Comment by sophokles73** [comment]
@kaklakariada it seems that the automatic release did not work for this PR ...

**Comment by kaklakariada** [comment]
Argh. I mixed up the release process with our process at work. Here we need to trigger the release workflow manually. And we should have entered the release date in the changelog file.

I will do the release on the weekend.

**Pull request merged**
