### PR TITLE
#189: Fixed ignored output format when using OFT CLI.

### PR DESCRIPTION
**Pull request by redcatbear**

### CODE REVIEW

**Comment by redcatbear** [comment]
Fixes #189.

**Comment by redcatbear** [comment]
@cruzel89, please review.

**Comment by cruzel89** [comment]
@redcatbear
I will retest this as soon as I can build the project (#188 is fixed), or is there a way to get a snapshot jar from CI? I looked into the linked CircleCI and Travis reports, but they do not seem to contain any jar artifacts.

**Comment by cruzel89** [comment]
Retest was successful here as well :+1:

**Pull request merged**
